# Generated by Django 6.0.2 on 2026-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
